services:
  - type: web
    name: whatsapp-server
    env: node
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
